version: "3"
services:
  db:
    image: postgres:14.1
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "woojo"
      POSTGRES_PASSWORD: "asd1234"
    volumes:
      - D:/postgresql/data/:/var/lib/postgresql/data